(function (){var h=!0,i=null,j=!1,aa=encodeURIComponent,k=window,l=Error,ba=parseInt,m=document,p=Array;function q(a,c){return a.innerHTML=c}function ca(a,c){return a.currentTarget=c}function da(a,c){return a.length=c}function ea(a,c){return a.className=c}
var r="appendChild",t="push",v="slice",w="replace",x="indexOf",fa="createElement",ga="firstChild",ha="setAttribute",y="type",ia="substr",ja="toString",z="length",ka="propertyIsEnumerable",la="title",A="prototype",B="split",ma="location",C="call",na="href",E="apply",F="join",oa="alternate",G;var H=this;function pa(){}function qa(a){a.B=function(){return a.na||(a.na=new a)}}
function I(a){var c=typeof a;if("object"==c)if(a){if(a instanceof p)return"array";if(a instanceof Object)return c;var b=Object[A][ja][C](a);if("[object Window]"==b)return"object";if("[object Array]"==b||"number"==typeof a[z]&&"undefined"!=typeof a.splice&&"undefined"!=typeof a[ka]&&!a[ka]("splice"))return"array";if("[object Function]"==b||"undefined"!=typeof a[C]&&"undefined"!=typeof a[ka]&&!a[ka]("call"))return"function"}else return"null";else if("function"==c&&"undefined"==typeof a[C])return"object";
return c}function ra(a){var c=I(a);return"array"==c||"object"==c&&"number"==typeof a[z]}function J(a){return"string"==typeof a}function sa(a){return"function"==I(a)}function ta(a){a=I(a);return"object"==a||"array"==a||"function"==a}function ua(a){return a[va]||(a[va]=++wa)}var va="closure_uid_"+Math.floor(2147483648*Math.random())[ja](36),wa=0;function xa(a,c){var b=p[A][v][C](arguments,1);return function(){var d=p[A][v][C](arguments);d.unshift[E](d,b);return a[E](this,d)}}
function K(a,c){function b(){}b.prototype=c[A];a.m=c[A];a.prototype=new b;a[A].constructor=a}var ya=/^[a-zA-Z0-9\-_.!~*'()]*$/;function za(a){a=""+a;return!ya.test(a)?aa(a):a}function Aa(a,c){if(c)return a[w](Ba,"&amp;")[w](Ca,"&lt;")[w](Da,"&gt;")[w](Ea,"&quot;");if(!Fa.test(a))return a;-1!=a[x]("&")&&(a=a[w](Ba,"&amp;"));-1!=a[x]("<")&&(a=a[w](Ca,"&lt;"));-1!=a[x](">")&&(a=a[w](Da,"&gt;"));-1!=a[x]('"')&&(a=a[w](Ea,"&quot;"));return a}var Ba=/&/g,Ca=/</g,Da=/>/g,Ea=/\"/g,Fa=/[&<>\"]/;
function Ga(a){var c={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},b=m[fa]("div");return a[w](Ha,function(d,f){var e=c[d];if(e)return e;if("#"==f.charAt(0)){var g=Number("0"+f[ia](1));isNaN(g)||(e=String.fromCharCode(g))}e||(q(b,d+" "),e=b[ga].nodeValue[v](0,-1));return c[d]=e})}
function Ia(a){return a[w](/&([^;]+);/g,function(c,b){switch(b){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==b.charAt(0)){var d=Number("0"+b[ia](1));if(!isNaN(d))return String.fromCharCode(d)}return c}})}
var Ha=/&([^;\s<&]+);?/g,L=p[A],Ja=L[x]?function(a,c,b){return L[x][C](a,c,b)}:function(a,c,b){b=b==i?0:0>b?Math.max(0,a[z]+b):b;if(J(a))return!J(c)||1!=c[z]?-1:a[x](c,b);for(;b<a[z];b++)if(b in a&&a[b]===c)return b;return-1},Ka=L.forEach?function(a,c,b){L.forEach[C](a,c,b)}:function(a,c,b){for(var d=a[z],f=J(a)?a[B](""):a,e=0;e<d;e++)e in f&&c[C](b,f[e],e,a)},La=L.every?function(a,c,b){return L.every[C](a,c,b)}:function(a,c,b){for(var d=a[z],f=J(a)?a[B](""):a,e=0;e<d;e++)if(e in f&&!c[C](b,f[e],
e,a))return j;return h};function M(a,c){return 0<=Ja(a,c)}function Ma(a,c){var b=Ja(a,c),d;(d=0<=b)&&L.splice[C](a,b,1);return d}function Na(a){return L.concat[E](L,arguments)}function Oa(a){if("array"==I(a))return Na(a);for(var c=[],b=0,d=a[z];b<d;b++)c[b]=a[b];return c}function Pa(a,c,b,d){return L.splice[E](a,Qa(arguments,1))}function Qa(a,c,b){return 2>=arguments[z]?L[v][C](a,c):L[v][C](a,c,b)}var Ra;function Sa(a){return(a=a.className)&&"function"==typeof a[B]?a[B](/\s+/):[]}
function Ta(a,c){var b=Sa(a),d=Qa(arguments,1),f;f=b;for(var e=0,g=0;g<d[z];g++)M(f,d[g])||(f[t](d[g]),e++);f=e==d[z];ea(a,b[F](" "));return f}function Ua(a,c){var b=Sa(a),d=Qa(arguments,1),f;f=b;for(var e=0,g=0;g<f[z];g++)M(d,f[g])&&(Pa(f,g--,1),e++);f=e==d[z];ea(a,b[F](" "));return f}function Va(a,c,b){for(var d in a)c[C](b,a[d],d,a)}var Wa="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");
function Xa(a,c){for(var b,d,f=1;f<arguments[z];f++){d=arguments[f];for(b in d)a[b]=d[b];for(var e=0;e<Wa[z];e++)b=Wa[e],Object[A].hasOwnProperty[C](d,b)&&(a[b]=d[b])}}var N,Ya,Za,$a;function ab(){return H.navigator?H.navigator.userAgent:i}$a=Za=Ya=N=j;var bb;if(bb=ab()){var cb=H.navigator;N=0==bb[x]("Opera");Ya=!N&&-1!=bb[x]("MSIE");Za=!N&&-1!=bb[x]("WebKit");$a=!N&&!Za&&"Gecko"==cb.product}var db=N,O=Ya,eb=$a,fb=Za,gb;
a:{var hb="",ib;if(db&&H.opera)var jb=H.opera.version,hb="function"==typeof jb?jb():jb;else if(eb?ib=/rv\:([^\);]+)(\)|;)/:O?ib=/MSIE\s+([^\);]+)(\)|;)/:fb&&(ib=/WebKit\/(\S+)/),ib)var kb=ib.exec(ab()),hb=kb?kb[1]:"";if(O){var lb,mb=H.document;lb=mb?mb.documentMode:void 0;if(lb>parseFloat(hb)){gb=""+lb;break a}}gb=hb}var nb=gb,ob={};
function P(a){var c;if(!(c=ob[a])){c=0;for(var b=(""+nb)[w](/^[\s\xa0]+|[\s\xa0]+$/g,"")[B]("."),d=(""+a)[w](/^[\s\xa0]+|[\s\xa0]+$/g,"")[B]("."),f=Math.max(b[z],d[z]),e=0;0==c&&e<f;e++){var g=b[e]||"",n=d[e]||"",o=RegExp("(\\d*)(\\D*)","g"),u=RegExp("(\\d*)(\\D*)","g");do{var s=o.exec(g)||["","",""],D=u.exec(n)||["","",""];if(0==s[0][z]&&0==D[0][z])break;c=((0==s[1][z]?0:ba(s[1],10))<(0==D[1][z]?0:ba(D[1],10))?-1:(0==s[1][z]?0:ba(s[1],10))>(0==D[1][z]?0:ba(D[1],10))?1:0)||((0==s[2][z])<(0==D[2][z])?
-1:(0==s[2][z])>(0==D[2][z])?1:0)||(s[2]<D[2]?-1:s[2]>D[2]?1:0)}while(0==c)}c=ob[a]=0<=c}return c}var pb={};function qb(a){return pb[a]||(pb[a]=O&&m.documentMode&&m.documentMode>=a)}!O||qb(9);!O||qb(9);O&&P("8");!fb||P("528");eb&&P("1.9b")||O&&P("8")||db&&P("9.5")||fb&&P("528");!eb||P("8");function rb(){}rb[A].ha=j;function Q(a,c){this.type=a;this.target=c;ca(this,this.target)}K(Q,rb);Q[A].S=j;Q[A].U=h;var sb={},R={},tb={},ub={};
function vb(a,c,b,d,f){if("array"==I(c)){for(var e=0;e<c[z];e++)vb(a,c[e],b,d,f);return i}d=!!d;a:{e=R;if(c in e&&(e=e[c],d in e&&(e=e[d],a=ua(a),e[a]))){a=e[a];break a}a=i}if(!a)return j;for(e=0;e<a[z];e++)if(a[e].Ja==b&&a[e].fa==d&&a[e].Ia==f)return wb(a[e].key);return j}
function wb(a){if(!sb[a])return j;var c=sb[a];if(c.T)return j;var b=c.src,d=c[y],f=c.za,e=c.fa;b.removeEventListener?(b==H||!b.ga)&&b.removeEventListener(d,f,e):b.detachEvent&&b.detachEvent(d in ub?ub[d]:ub[d]="on"+d,f);b=ua(b);f=R[d][e][b];if(tb[b]){var g=tb[b];Ma(g,c);0==g[z]&&delete tb[b]}c.T=h;f.ba=h;xb(d,e,b,f);delete sb[a];return h}
function xb(a,c,b,d){if(!d.J&&d.ba){for(var f=0,e=0;f<d[z];f++)d[f].T?d[f].za.src=i:(f!=e&&(d[e]=d[f]),e++);da(d,e);d.ba=j;0==e&&(delete R[a][c][b],R[a][c].A--,0==R[a][c].A&&(delete R[a][c],R[a].A--),0==R[a].A&&delete R[a])}}function yb(a,c,b,d,f){var e=1,c=ua(c);if(a[c]){a.C--;a=a[c];a.J?a.J++:a.J=1;try{for(var g=a[z],n=0;n<g;n++){var o=a[n];if(o&&!o.T){var u=e,s=o,D=s.handleEvent(f);s.Ha&&wb(s.key);e=u&D!==j}}}finally{a.J--,xb(b,d,c,a)}}return Boolean(e)}var zb=0;
function Ab(a){if(a[1]){var c=a[0],b=c[x]("#");0<=b&&(a[t](c[ia](b)),a[0]=c=c[ia](0,b));b=c[x]("?");0>b?a[1]="?":b==c[z]-1&&(a[1]=void 0)}return a[F]("")}var Bb=/#|$/,Cb=!O||qb(9);!eb&&!O||O&&qb(9)||eb&&P("1.9.1");O&&P("9");function Db(a,c){Va(c,function(b,d){"style"==d?a.style.cssText=b:"class"==d?ea(a,b):"for"==d?a.htmlFor=b:d in Eb?a[ha](Eb[d],b):0==d.lastIndexOf("aria-",0)?a[ha](d,b):a[d]=b})}
var Eb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};function Fb(a,c,b,d){function f(g){g&&c[r](J(g)?a.createTextNode(g):g)}for(;d<b[z];d++){var e=b[d];ra(e)&&!(ta(e)&&0<e.nodeType)?Ka(Gb(e)?Oa(e):e,f):f(e)}}
function S(a,c,b){var d=arguments,f=d[0],e=d[1];if(!Cb&&e&&(e.name||e[y])){f=["<",f];e.name&&f[t](' name="',Aa(e.name),'"');if(e[y]){f[t](' type="',Aa(e[y]),'"');var g={};Xa(g,e);e=g;delete e[y]}f[t](">");f=f[F]("")}f=m[fa](f);e&&(J(e)?ea(f,e):"array"==I(e)?Ta[E](i,[f].concat(e)):Db(f,e));2<d[z]&&Fb(m,f,d,2);return f}function Gb(a){if(a&&"number"==typeof a[z]){if(ta(a))return"function"==typeof a.item||"string"==typeof a.item;if(sa(a))return"function"==typeof a.item}return j}
function Hb(a){this.O=a||H.document||m}G=Hb[A];G.v=function(a){return J(a)?this.O.getElementById(a):a};G.createElement=function(a){return this.O[fa](a)};G.createTextNode=function(a){return this.O.createTextNode(a)};G.appendChild=function(a,c){a[r](c)};G.append=function(a,c){Fb(9==a.nodeType?a:a.ownerDocument||a.document,a,arguments,1)};function Ib(){}K(Ib,rb);G=Ib[A];G.ga=h;G.Q=i;G.V=function(a){this.Q=a};G.removeEventListener=function(a,c,b,d){vb(this,a,c,b,d)};
G.dispatchEvent=function(a){var c=a[y]||a,b=R;if(c in b){if(J(a))a=new Q(a,this);else if(a instanceof Q)a.target=a.target||this;else{var d=a,a=new Q(c,this);Xa(a,d)}var d=1,f,b=b[c],c=h in b,e;if(c){f=[];for(e=this;e;e=e.Q)f[t](e);e=b[h];e.C=e.A;for(var g=f[z]-1;!a.S&&0<=g&&e.C;g--)ca(a,f[g]),d&=yb(e,f[g],a[y],h,a)&&a.U!=j}if(j in b)if(e=b[j],e.C=e.A,c)for(g=0;!a.S&&g<f[z]&&e.C;g++)ca(a,f[g]),d&=yb(e,f[g],a[y],j,a)&&a.U!=j;else for(f=this;!a.S&&f&&e.C;f=f.Q)ca(a,f),d&=yb(e,f,a[y],j,a)&&a.U!=j;a=Boolean(d)}else a=
h;return a};function Jb(){}qa(Jb);Jb[A].ya=0;Jb.B();function T(a){a||Ra||(Ra=new Hb)}K(T,Ib);G=T[A];G.ma=Jb.B();function Kb(a,c){switch(a){case 1:return c?"disable":"enable";case 2:return c?"highlight":"unhighlight";case 4:return c?"activate":"deactivate";case 8:return c?"select":"unselect";case 16:return c?"check":"uncheck";case 32:return c?"focus":"blur";case 64:return c?"open":"close"}throw l("Invalid component state");}G.Z=i;G.$=j;G.u=i;G.R=i;G.N=i;G.G=i;
G.getId=function(){return this.Z||(this.Z=":"+(this.ma.ya++)[ja](36))};G.v=function(){return this.u};G.V=function(a){if(this.R&&this.R!=a)throw l("Method not supported");T.m.V[C](this,a)};G.I=function(){Lb(this,function(a){a.$&&a.I()});this.la&&this.la.Ka();this.$=j};function Lb(a,c,b){a.N&&Ka(a.N,c,b)}
G.removeChild=function(a,c){if(a){var b=J(a)?a:a.getId(),a=this.G&&b?(b in this.G?this.G[b]:void 0)||i:i;if(b&&a){var d=this.G;b in d&&delete d[b];Ma(this.N,a);c&&(a.I(),a.u&&a.u&&a.u.parentNode&&a.u.parentNode.removeChild(a.u));b=a;if(b==i)throw l("Unable to set parent component");b.R=i;T.m.V[C](b,i)}}if(!a)throw l("Child is not in parent component");return a};zb++;function U(){}var Mb;qa(U);G=U[A];
G.H=function(a,c,b){if(a=a.v?a.v():a)if(O&&!P("7")){var d=Nb(this,Sa(a),c);d[t](c);xa(b?Ta:Ua,a)[E](i,d)}else b?Ta(a,c):Ua(a,c)};G.da=function(a,c){var b;if(a.F&32&&(b=a.P())){if(!c&&a.j&32){try{b.blur()}catch(d){}a.j&32&&(a.W&4&&a.F&4&&a.setActive(j),a.W&32&&a.F&32&&Ob(a,32,j)&&a.z(32,j))}var f;(f=b.getAttributeNode("tabindex"))&&f.specified?(f=b.tabIndex,f="number"==typeof f&&0<=f&&32768>f):f=j;f!=c&&(c?b.tabIndex=0:(b.tabIndex=-1,b.removeAttribute("tabIndex")))}};
G.z=function(a,c,b){var d=a.v();if(d){var f;this.X||(f=this.Y(),this.X={1:f+"-disabled",2:f+"-hover",4:f+"-active",8:f+"-selected",16:f+"-checked",32:f+"-focused",64:f+"-open"});(f=this.X[c])&&this.H(a,f,b);this.L(d,c,b)}};G.L=function(a,c,b){Mb||(Mb={1:"disabled",8:"selected",16:"checked",64:"expanded"});(c=Mb[c])&&a[ha]("aria-"+c,b)};G.P=function(a){return a.v()};G.Y=function(){return"goog-control"};
function Nb(a,c,b){var d=[];b&&(c=c.concat([b]));Ka([],function(f){La(f,xa(M,c))&&(!b||M(f,b))&&d[t](f[F]("_"))});return d}function V(){}K(V,U);qa(V);V[A].L=function(a,c,b){16==c?a[ha]("aria-pressed",b):V.m.L[C](this,a,c,b)};V[A].Y=function(){return"goog-button"};O||fb&&P("525");function Pb(a,c){if(!a)throw l("Invalid class name "+a);if(!sa(c))throw l("Invalid decorator function "+c);}var Qb={};
function W(a,c,b){T[C](this,b);if(!(a=c)){for(var a=this.constructor,d;a;){d=ua(a);if(d=Qb[d])break;a=a.m?a.m.constructor:i}a=d?sa(d.B)?d.B():new d:i}this.D=a}K(W,T);G=W[A];G.j=0;G.F=39;G.W=255;G.Ea=0;G.Fa=h;G.g=i;G.P=function(){return this.D.P(this)};G.H=function(a,c){c?a&&(this.g?M(this.g,a)||this.g[t](a):this.g=[a],this.D.H(this,a,h)):a&&this.g&&(Ma(this.g,a),0==this.g[z]&&(this.g=i),this.D.H(this,a,j))};
G.I=function(){W.m.I[C](this);this.oa&&this.oa.detach();this.Fa&&!(this.j&1)&&this.D.da(this,j)};G.setActive=function(a){Ob(this,4,a)&&this.z(4,a)};G.z=function(a,c){this.F&a&&c!=!!(this.j&a)&&(this.D.z(this,a,c),this.j=c?this.j|a:this.j&~a)};function Ob(a,c,b){return!!(a.F&c)&&!!(a.j&c)!=b&&(!(a.Ea&c)||a.dispatchEvent(Kb(c,b)))&&!a.ha}if(!sa(W))throw l("Invalid component class "+W);if(!sa(U))throw l("Invalid renderer class "+U);var Rb=ua(W);Qb[Rb]=U;Pb("goog-control",function(){return new W(i)});
function X(){}K(X,V);qa(X);X[A].da=pa;X[A].z=function(a,c,b){X.m.z[C](this,a,c,b);if((a=a.v())&&1==c)a.disabled=b};X[A].L=pa;function Sb(a,c,b){W[C](this,a,c||X.B(),b)}K(Sb,W);Pb("goog-button",function(){return new Sb(i)});O&&P(8);var Tb;(Tb="ScriptEngine"in H&&"JScript"==H.ScriptEngine())&&(H.ScriptEngineMajorVersion(),H.ScriptEngineMinorVersion(),H.ScriptEngineBuildVersion());function Y(a,c){this.a=Tb?[]:"";a!=i&&this.append[E](this,arguments)}
Tb?(Y[A].M=0,Y[A].append=function(a,c,b){c==i?this.a[this.M++]=a:(this.a[t][E](this.a,arguments),this.M=this.a[z]);return this}):Y[A].append=function(a,c,b){this.a+=a;if(c!=i)for(var d=1;d<arguments[z];d++)this.a+=arguments[d];return this};Y[A].clear=function(){Tb?(da(this.a,0),this.M=0):this.a=""};Y[A].toString=function(){if(Tb){var a=this.a[F]("");this.clear();a&&this.append(a);return a}return this.a};
function Ub(a,c,b){a=a||m;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))c=a.querySelectorAll(b+(c?"."+c:""));else if(c&&a.getElementsByClassName)if(a=a.getElementsByClassName(c),b){for(var d={},f=0,e=0,g;g=a[e];e++)b==g.nodeName&&(d[f++]=g);da(d,f);c=d}else c=a;else if(a=a.getElementsByTagName(b||"*"),c){d={};for(e=f=0;g=a[e];e++)b=g.className,"function"==typeof b[B]&&M(b[B](/\s+/),c)&&(d[f++]=g);da(d,f);c=d}else c=a;if(1<=c[z])return c[0];throw l();}
function Vb(a){return m.createTextNode(a)}if(void 0===k._LOGIN_URL){var Wb;k._IS_MULTILOGIN_ENABLED?(Wb=Xb("AddSession",h),Wb+="&Email="+aa(_USER_EMAIL)):Wb=Xb("ServiceLogin",h);_LOGIN_URL=Wb}function Yb(a,c){if(c instanceof p){for(var b=0;b<c[z];b++)a=a[w]("%"+(b+1),c[b]);return a}return a[w]("%1",c)}
var Zb=RegExp("<(/s*(blockquote|body|center|dd|dir|div|dl|dt|form|h1|h2|h3|h4|h5|h6|head|html|hr|isindex|li|menu|noframes|ol|p|table|td|th|tr|title|ul)[^>]*|s*br[^>]*)>","gi"),$b=/<[^>]*>/gi,ac=/</g,bc=/>/g;function cc(a,c){if(!a)return"";c&&(a=a[w](Zb," "));a=a[w]($b,"");return a[w](ac,"&lt;")[w](bc,"&gt;")}function dc(a,c){if(a[z]<=c)return a;for(var b=a[B](/\s+/),d=[],f=0,e=0;e<b[z]&&f<=c;e++)d[t](b[e]),f+=b[e][z]+(e?1:0);a=d[F](" ");e!=b[z]&&(a+="...");return a}var ec={};
function fc(a){if(!(a in ec)){var c=ec,b;b=k[ma].search;var d=b.search(Bb),f;b:{f=0;for(var e=a[z];0<=(f=b[x](a,f))&&f<d;){var g=b.charCodeAt(f-1);if(38==g||63==g)if(g=b.charCodeAt(f+e),!g||61==g||38==g||35==g)break b;f+=e+1}f=-1}if(0>f)b=i;else{e=b[x]("&",f);if(0>e||e>d)e=d;f+=a[z]+1;b=decodeURIComponent(b[ia](f,e-f)[w](/\+/g," "))}c[a]=b}return ec[a]}function gc(a){fc("hl")&&(a=Ab([a,"&","hl","=",za("en")]));var c=fc("gl");c&&(a=Ab([a,"&","gl","=",za(c)]));return a}
function Xb(a,c){var b="https://www.google.com/accounts/"+a+"?service=reader&passive=true&nui=1&ltmpl=default";if(c){var d;try{d=k.top[ma][na]}catch(f){d=k[ma][na]}b+="&continue="+aa(d)+"&followup="+aa(d)}return b}
var Z={},hc={blue:{k:"#fff",i:"#bccceb",r:"#090992",o:"#bccceb",l:"#1010c8",f:"#7a7ee0",h:"#e5ecf9",e:"#898de9"},green:{k:"#fff",i:"#d8dbbc",r:"#2d8509",o:"#d8dbbc",l:"#58bf2f",f:"#97e07a",h:"#f5fbeb",e:"#adb094"},slate:{k:"#123",i:"#345",r:"#5e805e",o:"#5e6f80",l:"#abc",f:"#5e6f80",h:"#152939",e:"#abc"},gray:{k:"#fff",i:"#ccc",r:"#666",o:"#ccc",l:"#999",f:"#ccc",h:"#eee",e:"#aaa"},khaki:{k:"#f2e9ca",i:"#8e7c6a",r:"#d52",o:"#cba",l:"#543",f:"#ba9",h:"#eae0c6",e:"#987"},pink:{k:"#fff",i:"#aaa",r:"#d69",
o:"#ddd",l:"#e684ad",f:"#ebc",h:"#fcf0f7",e:"#a88"},black:{k:"#000",i:"#aaa",r:"#ccc",o:"#d8dbbc",l:"#d52",f:"#7a2b0e",h:"#111",e:"#999"}},ic={margin:0,padding:0,background:"transparent none",border:"none",textAlign:"left",textIndent:"0",textDecoration:"none",fontWeight:"normal"};
function jc(a,c){var b=kc(a);$(a,b.xa,c);if(a.ea){var d=S("h3");$(a,b.wa,d);d[r](Vb(a.ea));c[r](d)}d=S("ul");$(a,b.va,d);for(var f=0,e;e=a.d.items[f];f++)if(e[oa]){var g=S("li");$(a,b.ua,g);var n=S("a",{href:e[oa][na],title:e[la],"class":"i"});$(a,b.ra,n);var o=cc(e[la]||e.content);/^[\s\xa0]*$/.test(o==i?"":""+o)||(o=dc(o,48));n[r](Vb(o));g[r](n);if(a.Ca&&!a.aa&&e.origin[la]){var u=e.origin,n=S("div",{"class":"s"});$(a,b.ta,n);g[r](n);o=u[la];48<o[z]&&(o=o.substring(0,48));q(n,Yb("from <a>%1</a>",
o));u.htmlUrl&&(u=S("a",{href:u.htmlUrl}),q(u,o),$(a,b.sa,u),n.replaceChild(u,n.getElementsByTagName("a")[0]))}if(a.Ba&&!a.aa){n="";e=e.annotations||[];for(o=0;u=e[o];o++)if(-1!=a.d.id[x](u.userId)&&0<u.content[z]){n=u.content;break}0<n[z]&&(e=S("div"),$(a,b.qa,e),48<n[z]&&(n=n.substring(0,48)),q(e,'"'+n+'"'),g[r](e))}d[r](g)}c[r](d);d=S("div",{"class":"f"});$(a,b.ka,d);a.Da&&(f=S("a",{href:"http://www.google.com/webelements"}),$(a,b.Ga,f),d[r](f));if(a.d.id&&(f=-1!=a.d.id.search(/^user\/(\d+)\/bundle\//),
g=0==a.d.id.lastIndexOf("feed/",0),e=a.d[oa]&&a.d[oa][na],!g||f||e))if(e=S("a"),$(a,b.e,e),e[r](Vb("document"in H?Ga("View all &raquo;"):Ia("View all &raquo;"))),f){var s=gc("http://www.google.com/reader/bundle/"+a.d.id),f=lc({pa:s,Aa:"Preview &raquo;"});d[r](f);$(a,b.ja,Ub(f,"gr-bundle-table"));$(a,b.ia,Ub(f,"gr-show-all"));Ub(f,"gr-subscribe-button").onclick=function(){k[ma].href=s}}else e.href=g?a.d[oa][na]:gc("http://www.google.com/reader/shared/"+a.d.id),d[r](e);c[r](d)}
function kc(a){if("-"==a.ca)return{};a=hc[a.ca];return{xa:{fontFamily:"arial, sans-serif",fontSize:"10pt",background:a.k,border:"solid 1px "+a.i,margin:"0.5em"},wa:{padding:"0.2em 0.5em",background:a.h,borderBottom:"solid 1px "+a.o,color:a.r},va:{padding:"0.2em",margin:"0 0.5em",overflow:"hidden"},ua:{listStyleType:"none",padding:"0.4em 0 0.4em 0"},ra:{color:a.l,borderBottom:"solid 1px "+a.f},ta:{color:a.f},sa:{color:a.f},qa:{color:"#777",fontStyle:"italic"},ka:{textAlign:"right",borderTop:"solid 1px "+
a.i,background:a.h,padding:"0.2em 8px",fontSize:"small",whiteSpace:"nowrap",overflow:"hidden"},e:{color:a.e,textDecoration:"underline"},ja:{width:"100%"},ia:{textAlign:"right"},Ga:{cssFloat:"left",styleFloat:"left",display:"block",width:"130px",height:"20px",background:O&&7>nb?"none":"url(http://www.google.com/reader/ui/web-elements-logo.png)",filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(src=http://www.google.com/reader/ui/web-elements-logo.png,sizingMethod=crop)"}}}
function $(a,c,b){if(c){for(var d in ic)b.style[d]=ic[d];for(var f in c)b.style[f]=c[f]}}k.GRC_p=function(a){Z=a};
k.GRC=function(a,c){"GRC_c"in k||(k.GRC_c=0);this.K="readerpublishermodule"+k.GRC_c++;this.d=a;this.ca=Z.c;this.ea=Z.t;this.Ca="true"==Z.s;this.aa="true"==Z.b;this.Ba="true"==Z.n;this.Da="true"==Z.w;if(c)q(c,""),c.id=this.K,jc(this,m.getElementById(this.K));else{m.write('<div id="'+this.K+'" class="reader-publisher-module"></div>');var b=this;k.setTimeout(function(){jc(b,m.getElementById(b.K))},0)}};function lc(a,c){var b=c||new Y;b.append('<div><table class="gr-bundle-table"><tr><td><input class="gr-subscribe-button" type="button" value="',"Subscribe",'"></td><td class="gr-show-all"><a href="',Aa(""+a.pa),'">',a.Aa,"</a></td></tr></table></div>");if(!c){var d=b[ja](),b=m[fa]("div");O?(q(b,"<br>"+d),b.removeChild(b[ga])):q(b,d);if(1==b.childNodes[z])b=b.removeChild(b[ga]);else{for(d=m.createDocumentFragment();b[ga];)d[r](b[ga]);b=d}return b}};})();